# Generated by Django 3.2.12 on 2024-04-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_attraction_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='area',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attraction',
            name='url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
