# Generated by Django 3.2.12 on 2024-04-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20240402_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eamann',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
